Repository intellihr/ui-components, pull requests merged in 2020-06, with the labels that each got.

#819 [INT-12161] Remove unusable key prop and fix GridChild typing in gridlayout
  src/domain/Layouts/GridLayout/GridLayout.tsx
  src/domain/Layouts/GridLayout/subcomponents/Cell.tsx
Labels: PATCH

#824 Prevent PaginationButtons from submitting forms
  src/domain/Paginators/PaginationButtons/PaginationButtons.tsx
  src/domain/Paginators/PaginationButtons/__snapshots__/PaginationButtons.test.tsx.snap
Labels: PATCH

#826 Avoid left and right buttons from submitting the form
  src/domain/Paginators/PaginationButtons/PaginationButtons.tsx
  src/domain/Paginators/PaginationButtons/__snapshots__/PaginationButtons.test.tsx.snap
Labels: PATCH

#825 [INT-11590] Implement design changes for hierachical select.
  src/domain/Inputs/HierarchicalSelectInput/HierarchicalSelectInputOption.tsx
  src/domain/Inputs/HierarchicalSelectInput/TextMatch.tsx
  tsconfig.json
Labels: PATCH

#823 [INT-8469] Update Inter font download url
  src/common/sass/app.scss
Labels: PATCH

#828 [INT-12681] Add target prop to Card and GroupCard
  src/domain/Cards/Card/Card.examples.md
  src/domain/Cards/Card/Card.tsx
  src/domain/Cards/GroupCard/GroupCard.tsx
Labels: MINOR

#830 [INT-12701] allow for custom inputs in AddFilterDropdownMenu
  src/domain/Filters/AddFilterDropdownMenu/AddFilterDropdownMenu.examples.md
  src/domain/Filters/AddFilterDropdownMenu/AddFilterDropdownMenu.test.tsx
  src/domain/Filters/AddFilterDropdownMenu/AddFilterDropdownMenu.tsx
  src/domain/Filters/FilterController/FilterController.test.tsx
  src/domain/Filters/FilterController/FilterController.tsx
  src/domain/Filters/FilterController/__snapshots__/FilterController.test.tsx.snap
Labels: MINOR

#821 [INT-12452] Update avatar entity component
  src/common/types/props.ts
  src/domain/Avatars/AvatarEntity/AvatarEntity.examples.md
  src/domain/Avatars/AvatarEntity/AvatarEntity.test.tsx
  src/domain/Avatars/AvatarEntity/AvatarEntity.tsx
  src/domain/Avatars/AvatarEntity/__snapshots__/AvatarEntity.test.tsx.snap
  src/domain/Avatars/AvatarEntity/style.ts
  src/domain/Timelines/VerticalTimeline/VerticalTimelineEvent/__snapshots__/VerticalTimelineEvent.test.tsx.snap
Labels: MAJOR

#833 [INT-12452] fix on compact avatar entity
  src/domain/Avatars/AvatarEntity/AvatarEntity.examples.md
  src/domain/Avatars/AvatarEntity/AvatarEntity.tsx
  src/domain/Avatars/AvatarEntity/__snapshots__/AvatarEntity.test.tsx.snap
Labels: PATCH

#835 [INT-12672] Add condition label to form
  src/domain/Forms/VerticalForm/VerticalForm.examples.md
  src/domain/Forms/VerticalForm/subcomponents/Field.test.tsx
  src/domain/Forms/VerticalForm/subcomponents/Field.tsx
  src/domain/Forms/VerticalForm/subcomponents/__snapshots__/Field.test.tsx.snap
  src/domain/Forms/VerticalForm/subcomponents/style.ts
Labels: MINOR

#838 Update font awesome version to 15.13.1
  package.json
  src/domain/Icons/Icon/FontAwesomeIconTypes/types.ts
  yarn.lock
Labels: MAJOR
