Repository intellihr/ui-components, pull requests merged in 2020-05, with the labels that each got.

#783 [INT-11138] Add tbody to table
  src/domain/Tables/Table/Table.tsx
  src/domain/Tables/Table/__snapshots__/Table.test.tsx.snap
Labels: PATCH

#784 [INT-11096] Add delay to rerender so there is time to render with correct scroll.
  src/domain/Tabs/ScrollingTabGroup/ScrollingTabGroup.tsx
Labels: PATCH

#785 Fix unclickable space in table title.
  src/domain/Tables/Table/services/helper.ts
  src/domain/Tables/Table/services/style.ts
  src/domain/Tables/Table/subcomponents/TableHeader.tsx
Labels: PATCH

#788 Release 357
  package.json
  src/domain/Tables/Table/Table.tsx
  src/domain/Tables/Table/__snapshots__/Table.test.tsx.snap
  src/domain/Tables/Table/services/helper.ts
  src/domain/Tables/Table/services/style.ts
  src/domain/Tables/Table/subcomponents/TableHeader.tsx
  src/domain/Tables/Table/subcomponents/TableRow.tsx
  src/domain/Tables/Table/subcomponents/TableRowDataCell.tsx
  src/domain/Tabs/ScrollingTabGroup/ScrollingTabGroup.tsx
Labels: PATCH, release

#787 [INT-11124] Make pagination larger on mobile.
  src/domain/Paginators/PaginationButtons/style.ts
Labels: PATCH

#786 [INT-11105] Add backgroundColor prop to EmptyState
  src/domain/Callouts/EmptyState/EmptyState.examples.md
  src/domain/Callouts/EmptyState/EmptyState.tsx
  src/domain/Callouts/EmptyState/style.ts
  src/domain/Lists/SmartList/__snapshots__/SmartList.test.tsx.snap
Labels: MINOR

#790 Release 358
  package.json
  src/domain/Callouts/EmptyState/EmptyState.examples.md
  src/domain/Callouts/EmptyState/EmptyState.tsx
  src/domain/Callouts/EmptyState/style.ts
  src/domain/Lists/SmartList/__snapshots__/SmartList.test.tsx.snap
  src/domain/Paginators/PaginationButtons/style.ts
Labels: MINOR, release

#791 [INT-11170] Reduce the page count in the PaginationButtons component in mobile
  src/domain/Paginators/PaginationButtons/PaginationButtons.tsx
Labels: PATCH

#789 [INT-11166] Preset large icon size on swipe actions of table
  src/domain/Tables/Table/Table.examples.md
  src/domain/Tables/Table/services/helper.ts
  src/domain/Tables/Table/subcomponents/TableHeader.tsx
  src/domain/Tables/Table/subcomponents/TableRow.tsx
Labels: PATCH

#792 Show focus states more clearly on scrolling tab group.
  src/domain/Tabs/ScrollingTabGroup/style.ts
Labels: PATCH

#794 [INT-9603] Support full-screen modals
  src/common/types/props.ts
  src/domain/Modals/Modal/Modal.examples.md
  src/domain/Modals/Modal/Modal.tsx
  src/domain/Modals/Modal/__snapshots__/Modal.test.tsx.snap
  src/domain/Modals/Modal/style.tsx
Labels: MINOR

#795 Release 359
  package.json
  src/common/types/props.ts
  src/domain/Modals/Modal/Modal.examples.md
  src/domain/Modals/Modal/Modal.tsx
  src/domain/Modals/Modal/__snapshots__/Modal.test.tsx.snap
  src/domain/Modals/Modal/style.tsx
  src/domain/Paginators/PaginationButtons/PaginationButtons.tsx
  src/domain/Tables/Table/Table.examples.md
  src/domain/Tables/Table/services/helper.ts
  src/domain/Tables/Table/subcomponents/TableHeader.tsx
  src/domain/Tables/Table/subcomponents/TableRow.tsx
  src/domain/Tabs/ScrollingTabGroup/style.ts
Labels: MINOR, release

#796 [INT-11229] Create Draggable List
  package.json
  src/common/types/props.ts
  src/domain/Lists/DraggableList/DraggableList.examples.md
  src/domain/Lists/DraggableList/DraggableList.tsx
  src/domain/Lists/DraggableList/index.ts
  src/domain/Lists/DraggableList/style.ts
  src/domain/Lists/index.ts
  src/domain/index.ts
  styleguide.config.js
  yarn.lock
Labels: MINOR

#800 [INT-10541] Fix MenuItem hover styling
  src/domain/Menus/Menu/MenuItem/MenuItemContent/style.tsx
Labels: PATCH

#802 [INT-10220] Fix incorrect default css styles scope
  package.json
  rollup.config.js
  yarn.lock
Labels: PATCH

#804 [INT-12153] Update font awesome icon button type and button override
  src/domain/Buttons/FontAwesomeIconButton/FontAwesomeIconButton.tsx
  src/domain/Buttons/FontAwesomeIconButton/__snapshots__/FontAwesomeIconButton.test.tsx.snap
Labels: PATCH

#806 [INT-11615] Flip the position of status dot and status icon on Avatar component
  src/common/sass/legacy/components/_person-tag.scss
  src/domain/Avatars/Avatar/Avatar.examples.md
  src/domain/Avatars/Avatar/Avatar.scss
Labels: PATCH

#807 Mark CSS files to have side effects
  package.json
Labels: MAJOR

#809 [MINOR] Export styleForMargins.
  src/domain/Spacers/Margin/Margin.tsx
Labels: MINOR

#812 Fix package version.
  package.json
Labels: PATCH

#814 [INT-12242] Properly pass through keys in DraggableList
  src/domain/Lists/DraggableList/DraggableList.examples.md
  src/domain/Lists/DraggableList/DraggableList.tsx
Labels: PATCH

#815 [INT-12241] Stop draggable list from wiggling when a card is picked up
  src/domain/Lists/DraggableList/style.ts
Labels: PATCH

#817 [INT-12309] Add margins props to draggable list
  src/domain/Lists/DraggableList/DraggableList.tsx
  src/domain/Lists/DraggableList/style.ts
Labels: PATCH
