Repository intellihr/ui-components, pull requests merged in 2020-07, with the labels that each got.

#840 [INT-13011] Update tooltip popover default toggle component to be span instead of button
  src/domain/Formats/Record/__snapshots__/Record.test.tsx.snap
  src/domain/Popovers/TooltipPopover/TooltipPopover.tsx
  src/domain/Popovers/TooltipPopover/__snapshots__/TooltipPopover.test.tsx.snap
Labels: PATCH

#841 [INT-13089] Remove label suffix on form field
  src/domain/Forms/VerticalForm/VerticalForm.examples.md
  src/domain/Forms/VerticalForm/subcomponents/Field.test.tsx
  src/domain/Forms/VerticalForm/subcomponents/Field.tsx
  src/domain/Forms/VerticalForm/subcomponents/__snapshots__/Field.test.tsx.snap
  src/domain/Forms/VerticalForm/subcomponents/style.ts
Labels: PATCH

#842 [INT-13012] Add tooltip props to dropdown menu section
  src/domain/Popovers/DropdownMenu/DropdownMenu.examples.md
  src/domain/Popovers/DropdownMenu/DropdownMenu.test.tsx
  src/domain/Popovers/DropdownMenu/__snapshots__/DropdownMenu.test.tsx.snap
  src/domain/Popovers/DropdownMenu/subcomponents/Section.tsx
  src/domain/Popovers/DropdownMenu/subcomponents/style.ts
Labels: MINOR

#844 [INT-13012] Fix tooltip props on dropdown section
  src/domain/Popovers/DropdownMenu/DropdownMenu.examples.md
Labels: PATCH

#846 [INT-13177] Fix tooltip props on dropdown section
  src/domain/Popovers/DropdownMenu/subcomponents/Section.tsx
Labels: PATCH

#851 [INT-13668] Rename to Wonka Component Factory
  README.md
  styleguide.config.js
Labels: MINOR

#852 [INT-13688][INT-13687] Fix various issues with the table component.
  src/domain/Tables/Table/Table.examples.md
  src/domain/Tables/Table/Table.tsx
  src/domain/Tables/Table/__snapshots__/Table.test.tsx.snap
  src/domain/Tables/Table/subcomponents/TableRow.tsx
Labels: MAJOR

#850 [INT-13638] Add Dialog and Inline components
  src/common/sass/variables.ts
  src/common/types/props.ts
  src/domain/Layouts/Inline/Inline.examples.md
  src/domain/Layouts/Inline/Inline.tsx
  src/domain/Layouts/Inline/Item.tsx
  src/domain/Layouts/Inline/index.ts
  src/domain/Layouts/Inline/style.tsx
  src/domain/Layouts/index.ts
  src/domain/Modals/Dialog/Dialog.examples.md
  src/domain/Modals/Dialog/Dialog.tsx
  src/domain/Modals/Dialog/index.ts
  src/domain/Modals/Dialog/style.tsx
  src/domain/Modals/index.ts
  src/domain/Tabs/ScrollingTabGroup/ScrollingTabGroup.tsx
  src/domain/index.ts
  styleguide.config.js
Labels: MINOR
